package com.example.aipractice.dto;

/**
 * Response payload produced by an AI chat operation.
 *
 * @param message text generated by the model
 */
public record ChatResponse(
        String message
) {
}
