package com.example.aipractice.dto;

import java.util.List;

/**
 * Response payload produced by an AI chat operation.
 *
 * @param conversationId identifier of the conversation
 * @param message text generated by the model
 * @param sources knowledge files used to provide context for the response
 */
public record ChatResponse(
        String conversationId,
        String message,
        List<String> sources
) {
}
