package com.example.aipractice.client;

/**
 * Defines the application-facing contract for an AI chat provider.
 */
public interface AiClient {

    /**
     * Sends a user message to the configured AI provider.
     *
     * @param message message to send to the provider
     * @return text generated by the provider
     */
    String chat(String message);
}
