package com.example.aipractice.client;

import com.example.aipractice.exception.AiProviderException;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.stereotype.Component;

/**
 * Gemini-backed implementation of {@link AiClient} using Spring AI's
 * provider-neutral {@link ChatModel} abstraction.
 */
@Component
public class GeminiAiClient implements AiClient {

    private final ChatModel chatModel;

    /**
     * Creates a Gemini client backed by the auto-configured Spring AI model.
     *
     * @param chatModel Spring AI model used to submit chat requests
     */
    public GeminiAiClient(ChatModel chatModel) {
        this.chatModel = chatModel;
    }

    /**
     * Sends a message through Spring AI and returns Gemini's text response.
     *
     * @param message message to send to Gemini
     * @return non-blank text generated by Gemini
     * @throws AiProviderException if Gemini fails or returns no text
     */
    @Override
    public String chat(String message) {
        try {
            String response = chatModel.call(message);
            if (response == null || response.isBlank()) {
                throw new AiProviderException("Gemini returned no text content");
            }
            return response;
        } catch (AiProviderException exception) {
            throw exception;
        } catch (RuntimeException exception) {
            throw new AiProviderException("Gemini API request failed", exception);
        }
    }
}
